### ISSUE TITLE
Test: "must throw an error when posting to a non-existent or inaccessible channel" doesn't fully test

### ISSUE THREAD

**Issue by mrking** [mrking/SlackTogglReminders#1]
```
it("must throw an error when posting to a non-existent or inaccessible channel", function() {
      var channels = ['sith-lord-king', 'biz-setup'];

      channels.forEach(function(channel) {
        return slackAPI.postMessageToChannel("Once more the Sith will rule the galaxy, and we shall have peace", channel).then(function(result) {
          expect(result).to.be.true;
        }, function(err) {
          expect(err).to.exist;
        });
      });
    });
```

This function's second assertion test never gets tested because the first promise is the only one that's ever return. I would suggest using promise.all instead.

**Comment by tyronetan** [comment]
I think you're right in saying that the function's second assertion test never gets tested, but I don't think it's for the reasons you say. I think the intent of this test was to never hit the code where the promise resolves rather than reject. Where the first assertion is the path to resolution, the path to rejection has nowhere to go because I think it doesn't have a catch function for errors to go to. In fact, I'm questioning whether we coded the catches correctly, as the reject codes don't go to the then function after the a code block is ran to rejection.

**Comment by mrking** [comment]
The function is local to the forEach and has no communication with the test itself. Therefore neither has has an impact on the test's status. 

Furthermore, Promise.all won't work because of the nature of the test expecting to see an error. The only solution is to either split the test or chain promises. Promise...Then...Then... Then.
